// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://srblzbdikthvlkhkbkjd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNyYmx6YmRpa3RodmxraGtia2pkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzY1OTUsImV4cCI6MjA3MjQxMjU5NX0.1MgwFL481lJqegkYUXAw92Dz_YP6NwKfkOaB9R6UEhc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});